name: CI

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.5.1
      with:
            REMOTE: 'https://codeberg.org/liameno/librengine.git'
            GIT_USERNAME: liameno
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
